### ISSUE TITLE
在下载完数据集，配置好虚拟环境后，运行脚本文件提示报错如下：

### ISSUE THREAD

**Issue by star-rui** [zjunlp/PromptKG#34]
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    main()
  File "main.py", line 143, in main
    trainer.fit(lit_model, datamodule=data)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 842, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1107, in run_sanity_check
    self.run_evaluation()
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 962, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 174, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 221, in validation_step
    batch = self.to_device(args[0])
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu.py", line 69, in to_device
    batch = super().to_device(batch)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 394, in to_device
    return self.batch_to_device(batch, self.root_device)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 177, in batch_to_device
    return model._apply_batch_transfer_handler(batch, device)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 216, in _apply_batch_transfer_handler
    batch = self.transfer_batch_to_device(batch, device)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/core/hooks.py", line 704, in transfer_batch_to_device
    return move_data_to_device(batch, device)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 161, in move_data_to_device
    return apply_to_collection(batch, dtype=dtype, function=batch_to)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 84, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 158, in batch_to
    return data.to(device, **kwargs)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/transformers/file_utils.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/root/.local/conda/envs/genkgc/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 738, in to
    v.to(device=device)
AttributeError: 'list' object has no attribute 'to'

但是tokenization_utils_base.py是下载的transformers安装包中的，为什么会在这里报错嘞？请问作者遇到过这个问题吗，感谢您的回答！

**Comment by CheaSim** [comment]
你好，请说明一下运行的脚本具体是哪一个，可能由于transformers版本问题报错。

**Comment by star-rui** [comment]
您好，运行的脚本是./fb15k.sh这个脚本，使用pip list显示transformers             4.7.0,我是在九天毕昇的服务器平台上运行的。我再重新安装一下transformers，感谢作者！ღ( ´･ᴗ･` )

**Comment by zhui-coder** [comment]
> 您好，运行的脚本是./fb15k.sh这个脚本，使用pip list显示transformers 4.7.0,我是在九天毕昇的服务器平台上运行的。我再重新安装一下transformers，感谢作者！ღ( ´･ᴗ･` )

您好，我也遇到了同样的问题，请问您是怎么解决的呀
