### ISSUE TITLE
作者您好，请问想要使用GenKGC模型来训练给出的阿里中文数据集，在执行openbg.sh脚本文件前还需要做什么其他操作吗，现在两个英文数据集可以正常运行，但是中文数据集运行失败了

### ISSUE THREAD

**Issue by star-rui** [zjunlp/PromptKG#42]

**Comment by CheaSim** [comment]
你好，针对中文数据集需要将backbone model换成中文的bart，如[fnlp/bart-base-chinese](https://huggingface.co/fnlp/bart-base-chinese). 如果仍然有运行错误，可以将您的错误截图贴出来。

**Comment by star-rui** [comment]
作者您好，目前运行遇到的错误如下，现在还没把这个报错解决，
$ /bin/sh E:/project/GenKGC/openbg.sh
Global seed set to 7
tokenize the prefix tree:   0%|                                                                                                                                                   | 0/269658 [00:00<?, ?it/s]
定妆喷雾 [101, 8335, 7816, 6857, 23292, 102]
普通装 [101, 11072, 21562, 19731, 102]
长袖上衣 [101, 22915, 19684, 4906, 19633, 102]
常规 [101, 8992, 19977, 102]
T恤 [101, 156, 9545, 102]
tokenize the prefix tree: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 269658/269658 [00:27<00:00, 9920.46it/s]
**********max output length : 128**********
total 0 cannot be tokenized
Traceback (most recent call last):
  File "main.py", line 159, in <module>
    main()
  File "main.py", line 101, in main
    params_dict = torch.load(args.checkpoint, map_location="cpu")['state_dict']
  File "D:\Anaconda\anaconda\envs\genkgc\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Anaconda\anaconda\envs\genkgc\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Anaconda\anaconda\envs\genkgc\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'output/epoch=5-Eval/hits10=0.25.ckpt'

**Comment by star-rui** [comment]
作者您好，在openbg.sh这个脚本文件中，提到的output/epoch=5-Eval/hits10=0.25.ckpt  这个权重文件，没有在项目中找到，请问能否麻烦您发到我的邮箱lirx1010@163.com，现在不能加载预训练的权重文件，代码无法执行成功。
非常感谢！！

**Comment by CheaSim** [comment]
您好，运行`openbg.sh`时只需要使用facebook的中文bart-base的预训练权重，不需要checkpoint这个参数，目前已经修改了对应的代码。

**Comment by abc-Star** [comment]
作者，您好。代码执行到/data/processor.py中590行，报错信息如下，但openbg数据集下载链接中并没有features_train.txt，请问需要补齐这个文件吗

Traceback (most recent call last):
  File "main.py", line 159, in <module>
    main()
  File "main.py", line 141, in main
    trainer.fit(lit_model, datamodule=data)  # 训练和验证
  File "D:\Anaconda\anaconda\envs\genkgc\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 458, in fit
    self._run(model)
    return trainer.init_optimizers(model)
  File "D:\Anaconda\anaconda\envs\genkgc\lib\site-packages\pytorch_lightning\trainer\optimizers.py", line 34, in init_optimizers
    optim_conf = model.configure_optimizers()
  File "E:\project\GenKGC\lit_models\transformer.py", line 245, in configure_optimizers
    scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=self.num_training_steps * self.args.warm_up_radio, num_training_steps=self.num_training_steps)
  File "E:\project\GenKGC\lit_models\base.py", line 82, in num_training_steps
    dataset_size = len(self.trainer.datamodule.train_dataloader())
  File "D:\Anaconda\anaconda\envs\genkgc\lib\site-packages\torch\utils\data\dataloader.py", line 391, in __len__
    length = self._IterableDataset_len_called = len(self.dataset)  # type: ignore
  File "E:\project\GenKGC\data\processor.py", line 605, in __len__
    return len(open(self.file_name, 'r').readlines()) // 2
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/AliOpenKG500\\features_train.txt'
