### ISSUE TITLE
关于运行KGEditor的问题

### ISSUE THREAD

**Issue by haishengLuo** [zjunlp/PromptKG#54]
您好，我在运行您的KGEditor模型，我出现了两个问题
1. 我在RTX 4090D 显卡上面运行您的模型，发现与您在论文中所展现出来的运行结果相差较大，以下我的运行结果
  bash run.sh -m KGEditor -d FB15k237 -t edit
Eval/hits5 0.9883344134802333
Eval/hits3 0.9850939727802981
Eval/hits1 0.8716785482825664
Eval/mean_rank 4.06351263771873
Eval/mrr 0.9293085060783861
Eval/loc_hits1 0.5336195722618277
Eval/loc_hits3 0.880103694102398
Eval/loc_hits5 0.9589274141283215
Eval/loc_mean_rank 6.953742709008425
Eval/loc_mrr 0.706480117196983

 bash run.sh -m KGEditor -d WN18RR -t edit
Eval/hits5 0.5278571428571428
Eval/hits3 0.49
Eval/hits1 0.4042857142857143
Eval/mean_rank 1969.93
Eval/mrr 0.46629092281903356
Eval/loc_hits1 0.79875
Eval/loc_hits3 0.9716071428571429
Eval/loc_hits5 0.9898214285714285
Eval/loc_mean_rank 1.9782142857142857
Eval/loc_mrr 0.8852234423994798

bash run.sh -m KGEditor -d FB15k237 -t add
epoch =15 最好的数据指标
Eval/hits5 0.813
Eval/hits3 0.766
Eval/hits1 0.4815
Eval/mean_rank 51.551
Eval/mrr 0.630491583445402
Eval/loc_hits1 0.554875
Eval/loc_hits3 0.912
Eval/loc_hits5 0.962
Eval/loc_mean_rank 11.8675
Eval/loc_mrr 0.7349192120742428

epoch=20
Eval/hits5 0.7015
Eval/hits3 0.581
Eval/hits1 0.283
Eval/mean_rank 43.726
Eval/mrr 0.4640368920896744
Eval/loc_hits1 0.546875
Eval/loc_hits3 0.9165
Eval/loc_hits5 0.96175
Eval/loc_mean_rank 6.974625
Eval/loc_mrr 0.7309259631013995

2.当我运行    bash run.sh -m KGEditor -d WN18RR -t add指令时，训练到epoch=2或者epoch=3时出现了报错，以下是报错结果
Traceback (most recent call last):                                                                                                                             
  File "models/KGEditor/run.py", line 108, in <module>
    trainer.fit(model)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 869, in run_train
    self.train_loop.run_training_epoch()
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 490, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 731, in run_training_batch
    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 424, in optimizer_step
    model_ref.optimizer_step(
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1403, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 214, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 134, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 329, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 336, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 193, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/optim/rmsprop.py", line 102, in step
    loss = closure()
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 725, in train_step_and_backward_closure
    result = self.training_step_and_backward(
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 814, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 280, in training_step
    training_step_output = self.trainer.accelerator.training_step(args)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 204, in training_step
    return self.training_type_plugin.training_step(*args)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 319, in training_step
    return self.model(*args, **kwargs)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 46, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/root/autodl-tmp/PromptKG/deltaKG/src/models/models.py", line 465, in training_step
    kl, lp, cr = self.get_kl_lp_cr(logits_orig, logits, batch['label'],
  File "/root/autodl-tmp/PromptKG/deltaKG/src/models/models.py", line 444, in get_kl_lp_cr
    torch.distributions.Categorical(
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/distributions/categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/distributions/distribution.py", line 55, in __init__
    raise ValueError(
ValueError: Expected parameter probs (Tensor of shape (8, 40943)) of distribution Categorical(probs: torch.Size([8, 40943])) to satisfy the constraint Simplex(), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
       grad_fn=<DivBackward0>)
希望您可以给出一些指导意见，谢谢您的观看，给您添麻烦了！

**Comment by cheng-siyuan** [comment]
首先感谢你对我们工作的关注

1、这里运行结果的差异有可能是环境和版本的原因，我们之前运行的GPU式3090 CUDA这些版本的不同也可能导致结果的差异，我在这里给你提供我们的训练和结果日志。[LOG](https://drive.google.com/file/d/1DCBUzs3F3sbARo3bWEmN6OPnu2XAJROP/view?usp=drive_link)

2、这里出现nan报错我认为原因可能出现在更新模型过程中，请你主要检查更新中的loss以及传导的梯度，这样可以找到第一个出现nan的点，就可以定位到问题的原因在哪。

**Comment by haishengLuo** [comment]
> 首先感谢你对我们工作的关注
> 
> 1、这里运行结果的差异有可能是环境和版本的原因，我们之前运行的GPU式3090 CUDA这些版本的不同也可能导致结果的差异，我在这里给你提供我们的训练和结果日志。[LOG](https://drive.google.com/file/d/1DCBUzs3F3sbARo3bWEmN6OPnu2XAJROP/view?usp=drive_link)
> 
> 2、这里出现nan报错我认为原因可能出现在更新模型过程中，请你主要检查更新中的loss以及传导的梯度，这样可以找到第一个出现nan的点，就可以定位到问题的原因在哪。

好的，非常感谢

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by Chelsea0579** [comment]
> 您好，我在运行您的KGEditor模型，我出现了两个问题
> 
> 1. 我在RTX 4090D 显卡上面运行您的模型，发现与您在论文中所展现出来的运行结果相差较大，以下我的运行结果
>    bash run.sh -m KGEditor -d FB15k237 -t edit
>    Eval/hits5 0.9883344134802333
>    Eval/hits3 0.9850939727802981
>    Eval/hits1 0.8716785482825664
>    Eval/mean_rank 4.06351263771873
>    Eval/mrr 0.9293085060783861
>    Eval/loc_hits1 0.5336195722618277
>    Eval/loc_hits3 0.880103694102398
>    Eval/loc_hits5 0.9589274141283215
>    Eval/loc_mean_rank 6.953742709008425
>    Eval/loc_mrr 0.706480117196983
> 
> bash run.sh -m KGEditor -d WN18RR -t edit Eval/hits5 0.5278571428571428 Eval/hits3 0.49 Eval/hits1 0.4042857142857143 Eval/mean_rank 1969.93 Eval/mrr 0.46629092281903356 Eval/loc_hits1 0.79875 Eval/loc_hits3 0.9716071428571429 Eval/loc_hits5 0.9898214285714285 Eval/loc_mean_rank 1.9782142857142857 Eval/loc_mrr 0.8852234423994798
> 
> bash run.sh -m KGEditor -d FB15k237 -t add epoch =15 最好的数据指标 Eval/hits5 0.813 Eval/hits3 0.766 Eval/hits1 0.4815 Eval/mean_rank 51.551 Eval/mrr 0.630491583445402 Eval/loc_hits1 0.554875 Eval/loc_hits3 0.912 Eval/loc_hits5 0.962 Eval/loc_mean_rank 11.8675 Eval/loc_mrr 0.7349192120742428
> 
> epoch=20 Eval/hits5 0.7015 Eval/hits3 0.581 Eval/hits1 0.283 Eval/mean_rank 43.726 Eval/mrr 0.4640368920896744 Eval/loc_hits1 0.546875 Eval/loc_hits3 0.9165 Eval/loc_hits5 0.96175 Eval/loc_mean_rank 6.974625 Eval/loc_mrr 0.7309259631013995
> 
> 2.当我运行 bash run.sh -m KGEditor -d WN18RR -t add指令时，训练到epoch=2或者epoch=3时出现了报错，以下是报错结果 Traceback (most recent call last): File "models/KGEditor/run.py", line 108, in trainer.fit(model) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit self._run(model) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run self.dispatch() File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch self.accelerator.start_training(self) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training self.training_type_plugin.start_training(trainer) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training self._results = trainer.run_stage() File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage return self.run_train() File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 869, in run_train self.train_loop.run_training_epoch() File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 490, in run_training_epoch batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 731, in run_training_batch self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 424, in optimizer_step model_ref.optimizer_step( File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1403, in optimizer_step optimizer.step(closure=optimizer_closure) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 214, in step self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 134, in __optimizer_step trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 329, in optimizer_step self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 336, in run_optimizer_step self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 193, in optimizer_step optimizer.step(closure=lambda_closure, **kwargs) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper return wrapped(*args, **kwargs) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/optim/optimizer.py", line 113, in wrapper return func(*args, **kwargs) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/optim/rmsprop.py", line 102, in step loss = closure() File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 725, in train_step_and_backward_closure result = self.training_step_and_backward( File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 814, in training_step_and_backward result = self.training_step(split_batch, batch_idx, opt_idx, hiddens) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 280, in training_step training_step_output = self.trainer.accelerator.training_step(args) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 204, in training_step return self.training_type_plugin.training_step(*args) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 319, in training_step return self.model(*args, **kwargs) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward output = self._run_ddp_forward(*inputs, **kwargs) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward return module_to_run(*inputs[0], **kwargs[0]) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 46, in forward output = self.module.training_step(*inputs, **kwargs) File "/root/autodl-tmp/PromptKG/deltaKG/src/models/models.py", line 465, in training_step kl, lp, cr = self.get_kl_lp_cr(logits_orig, logits, batch['label'], File "/root/autodl-tmp/PromptKG/deltaKG/src/models/models.py", line 444, in get_kl_lp_cr torch.distributions.Categorical( File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/distributions/categorical.py", line 64, in **init** super(Categorical, self).**init**(batch_shape, validate_args=validate_args) File "/root/miniconda3/envs/deltakg/lib/python3.8/site-packages/torch/distributions/distribution.py", line 55, in **init** raise ValueError( ValueError: Expected parameter probs (Tensor of shape (8, 40943)) of distribution Categorical(probs: torch.Size([8, 40943])) to satisfy the constraint Simplex(), but found invalid values: tensor([[nan, nan, nan, ..., nan, nan, nan], [nan, nan, nan, ..., nan, nan, nan], [nan, nan, nan, ..., nan, nan, nan], ..., [nan, nan, nan, ..., nan, nan, nan], [nan, nan, nan, ..., nan, nan, nan], [nan, nan, nan, ..., nan, nan, nan]], device='cuda:0', grad_fn=) 希望您可以给出一些指导意见，谢谢您的观看，给您添麻烦了！

你好，我想问一下你的问题解决了吗，我也是运行出来的结果差距较大，除了“bash run.sh -m KGEditor -d FB15k237 -t edit”这个任务？谢谢！

**Comment by zxlzr** [comment]
> Chelsea0579

您好，gpu和cuda版本可能会导致结果差异（比如精度等因素），建议您多调试。我们提供了之前的log 参见之前的信息。

**Comment by Chelsea0579** [comment]
抱歉，之前的log没有访问权限，能否提供一下，感谢!

**Comment by zxlzr** [comment]
您好，已开通权限
