### ISSUE TITLE
运行lambdakg出现报错

### ISSUE THREAD

**Issue by bangiu** [zjunlp/PromptKG#60]
finished data processing... costing 0.26227760314941406s...
/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:611: UserWarning: Checkpoint directory output/WN18RR exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [4]
/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:2109: LightningDeprecationWarning: `Trainer.num_gpus` was deprecated in v1.6 and will be removed in v1.8. Please use `Trainer.num_devices` instead.
  rank_zero_deprecation(
/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:2077: LightningDeprecationWarning: `Trainer.num_processes` is deprecated in v1.6 and will be removed in v1.8. Please use `Trainer.num_devices` instead.
  rank_zero_deprecation(
/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:2093: LightningDeprecationWarning: `Trainer.tpu_cores` is deprecated in v1.6 and will be removed in v1.8. Please use `Trainer.num_devices` instead.
  rank_zero_deprecation(

  | Name      | Type             | Params
-----------------------------------------------
0 | model     | KGBERTModel      | 102 M 
1 | criterion | CrossEntropyLoss | 0     
2 | metric    | Accuracy         | 0     
-----------------------------------------------
102 M     Trainable params
0         Non-trainable params
102 M     Total params
409.077   Total estimated model params size (MB)
Epoch 0: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 1288/1288 [02:17<00:00,  9.35it/s, loss=0.7, v_num=0jen]
Traceback (most recent call last):                                                                                                                               
  File "main.py", line 154, in <module>
    main()
  File "main.py", line 136, in main
    trainer.fit(lit_model, datamodule=data)
  File "/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1351, in _run_train
    self.fit_loop.run()
  File "/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 205, in run
    self.on_advance_end()
  File "/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 296, in on_advance_end
    self.trainer._call_callback_hooks("on_train_epoch_end")
  File "/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1634, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 179, in on_train_epoch_end
    self._run_early_stopping_check(trainer)
  File "/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 190, in _run_early_stopping_check
    if trainer.fast_dev_run or not self._validate_condition_metric(  # disable early_stopping with fast_dev_run
  File "/data/server07/anaconda3/envs/lambdakg/lib/python3.8/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 145, in _validate_condition_metric
    raise RuntimeError(error_msg)
RuntimeError: Early stopping conditioned on metric `hits10` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `acc`
请问这种报错该如何解决呢

**Comment by CheaSim** [comment]
please check your pytorch_lightning version, suggest `pip install -r requirements.txt`  under the folder of the project.

**Comment by zxlzr** [comment]
hi, have you solved your issue yet?
